version: '3.4'

services:
  developmentrepository.server:
    image: ${DOCKER_REGISTRY-}developmentrepositoryserver
    build:
      context: .
      dockerfile: developmentrepository.Server/Dockerfile